### ISSUE TITLE
Please provide actual vanilla JS examples

### ISSUE THREAD

**Issue by alexspurling** [danchitnis/WebGL-plot-examples#31]
I work in an environment that cannot support compiled javascript (my html code must be served from an embedded device with limited memory). Please could you provide an example that loads the webgl library as an external dependency (i.e. script tag pointing to a .js file) and which uses plain javascript rather than Typescript.

**Comment by danchitnis** [comment]
Typically the best practice is to use a bundler like Webpack or Rollup to bundle all you JS code into one loadable script in the browser. For this you need a Node environment for development only. If you want to use a pre-bundled script tag and then add your own code in HTML or another script, then typically this is not a good practice unless your code base is too small. So which one the two is your case?

**Comment by alexspurling** [comment]
If it's considered bad practice to use external .js scripts then I can understand why you would want to discourage that. Also, if I can use webpack or rollup to bundle the code into a single script while minimising the size of the payload then I will attempt to go that route.

**Comment by danchitnis** [comment]
I have added examples for the pre-bundled script in the [ReadMe](https://github.com/danchitnis/webgl-plot#js-bundle). If you want to make your own bundle, then I recommend using Rollup, you can can see [here](https://github.com/danchitnis/benchtop-demo-lidar/tree/master/Plot) for an example.
