### ISSUE TITLE
replace text link to repository with GitHub Corner

### ISSUE THREAD

**Issue by hirehamir** [danchitnis/WebGL-plot-examples#76]
**Is your feature request related to a problem? Please describe.**
No problem here! I just think a [GitHub Corner](https://github.com/tholman/github-corners) would look nicer.

**Describe the solution you'd like**
Replace the text link to this repository with a [GitHub Corner](https://github.com/tholman/github-corners), instead.

**Describe alternatives you've considered**
Replacing the text at the bottom with just the GitHub logo at the top, but I think the [GitHub Corner](https://github.com/tholman/github-corners) implementation is more elegant.

**Additional context**
[GitHub Corner](https://github.com/tholman/github-corners) link

**Comment by danchitnis** [comment]
Merged. Thanks for this, I may apply to other pages too. 👍

**Comment by hirehamir** [comment]
You're welcome! Happy to help.
