### ISSUE TITLE
Missing Package.json

### ISSUE THREAD

**Issue by DrakoPOD** [danchitnis/WebGL-plot-examples#95]
Has several missing dependency issues. Doesn't run properly, some examples don't work. Also, when you click a link, doesn't use relative path. I mean, I open in `c://users/user/webgl-plot-examples/index.html` but when I click on a link send me to `c://vanilla/someexample.html`

**Comment by danchitnis** [comment]
@DrakoPOD which instructions did you follow?

**Comment by DrakoPOD** [comment]
@danchitnis 
```
git clone https://github.com/danchitnis/webgl-plot-examples.git
cd webgl-plot-examples
npm i
npm run build
```

**Comment by danchitnis** [comment]
@DrakoPOD follow the instructions (here)[https://github.com/danchitnis/webgl-plot] and then look at source code either in the `./vanilla/src/` folder or by clicking F12 in your browser.

There is no need to build these examples, they are pure javascript hence the name vanilla! just open each example in the browser.
